package in.gov.irms.train.enums;

public enum TrainType {

    OTHERS,
    GOODS,
    RAJDHANI,
    SHATABDI,
    DURONTO,
    VANDE_BHARAT,
    SUPERFAST_EXPRESS,
    MAIL_EXPRESS,
    GARIB_RATH,
    SAMPARK_KRANTI,
    HUMSAFAR,
    TEJAS,
    JAN_SHATABDI,
    DECCAN_QUEEN,
    MEMU,
    PASSENGER,
    INTERCITY,
    MAHARAJA_EXP,
    PALACE_ON_WHEELS,
    DECCAN_ODYSSEY,
    GOLDEN_CHARIOT,
    SUVIDHA_EXP,
    TOURIST_TRAIN,
    FESTIVAL_SPECIAL
}
